name: E2E tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  BLOCK_NUMBER: "14633843"
  DAI_WHALE: "0xe78388b4ce79068e89bf8aa7f218ef6b9ab0e9d0"
  USDC_WHALE: "0x47ac0fb4f2d84898e4d9e7b4dab3c24507a6d503"
  STKAAVE_WHALE: "0x32b61bb22cbe4834bc3e73dce85280037d944a4d"
  EMISSION_MANAGER: "0xEE56e2B3D491590B5b31738cC34d5232F378a8D5"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests:
          [
            "static_a_token.test.ts",
            "proxy.test.ts",
            "bridge.test.ts",
            "wad_ray_math.test.ts",
          ]
        python-version: ["3.9.0"] # Cairo was tested with this version
        node-version: ["16"]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          make

      - name: Start the l2 & l1 test networks
        run: |
          yarn testnet:l2 &
          yarn testnet:l1 &

      - name: Compile Cairo
        run: |
          yarn compile:l2

      - name: Run tests
        run: |
          yarn test test/${{ matrix.tests }}
